// Code generated by a script. DO NOT EDIT.
package mikrotik

import (
	"context"
	"github.com/ddelnano/terraform-provider-mikrotik/client"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceScheduler() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceSchedulerCreate,
		ReadContext:   resourceSchedulerRead,
		UpdateContext: resourceSchedulerUpdate,
		DeleteContext: resourceSchedulerDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type: schema.TypeString,

				Required: true,
				Optional: false,
				Computed: false,
			},
			"on_event": {
				Type: schema.TypeString,

				Required: true,
				Optional: false,
				Computed: false,
			},
			"start_date": {
				Type: schema.TypeString,

				Required: false,
				Optional: false,
				Computed: true,
			},
			"start_time": {
				Type: schema.TypeString,

				Required: false,
				Optional: false,
				Computed: true,
			},
			"interval": {
				Type: schema.TypeInt,

				Required: false,
				Optional: true,
				Computed: false,
			},
		},
	}
}

func resourceSchedulerCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	record := dataToScheduler(d)

	c := m.(*client.Mikrotik)

	mikrotikRecord, err := c.AddScheduler(record)
	if err != nil {
		return diag.FromErr(err)
	}

	return schedulerToData(mikrotikRecord, d)
}

func resourceSchedulerRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)

	record, err := c.FindScheduler(d.Id())

	if _, ok := err.(*client.NotFound); ok {
		d.SetId("")
		return nil
	}

	return schedulerToData(record, d)
}

func resourceSchedulerUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)

	currentRecord, err := c.FindScheduler(d.Id())
	record := dataToScheduler(d)
	record.Id = currentRecord.Id

	if err != nil {
		return diag.FromErr(err)
	}

	updatedRecord, err := c.UpdateScheduler(record)
	if err != nil {
		return diag.FromErr(err)
	}

	return schedulerToData(updatedRecord, d)
}

func resourceSchedulerDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)
	id := d.Id()

	err := c.DeleteScheduler(id)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

func dataToScheduler(d *schema.ResourceData) *client.Scheduler {
	record := new(client.Scheduler)

	record.Name = d.Get("name").(string)
	record.OnEvent = d.Get("on_event").(string)
	record.StartDate = d.Get("start_date").(string)
	record.StartTime = d.Get("start_time").(string)
	record.Interval = d.Get("interval").(int)

	return record
}

func schedulerToData(record *client.Scheduler, d *schema.ResourceData) diag.Diagnostics {
	values := map[string]interface{}{
		"name":       record.Name,
		"on_event":   record.OnEvent,
		"start_date": record.StartDate,
		"start_time": record.StartTime,
		"interval":   record.Interval,
	}

	d.SetId(record.Name)

	var diags diag.Diagnostics

	for key, value := range values {
		if err := d.Set(key, value); err != nil {
			diags = append(diags, diag.Errorf("failed to set %s: %v", key, err)...)
		}
	}

	return diags
}
