// Code generated by a script. DO NOT EDIT.
package mikrotik

import (
	"context"
	"github.com/ddelnano/terraform-provider-mikrotik/client"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourcePool() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourcePoolCreate,
		ReadContext:   resourcePoolRead,
		UpdateContext: resourcePoolUpdate,
		DeleteContext: resourcePoolDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type: schema.TypeString,

				Required: true,
				Optional: false,
				Computed: false,
			},
			"ranges": {
				Type: schema.TypeString,

				Required: true,
				Optional: false,
				Computed: false,
			},
			"comment": {
				Type: schema.TypeString,

				Required: false,
				Optional: true,
				Computed: false,
			},
		},
	}
}

func resourcePoolCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	record := dataToPool(d)

	c := m.(*client.Mikrotik)

	mikrotikRecord, err := c.AddPool(record)
	if err != nil {
		return diag.FromErr(err)
	}

	return poolToData(mikrotikRecord, d)
}

func resourcePoolRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)

	record, err := c.FindPool(d.Id())

	if _, ok := err.(*client.NotFound); ok {
		d.SetId("")
		return nil
	}

	return poolToData(record, d)
}

func resourcePoolUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)

	currentRecord, err := c.FindPool(d.Id())
	record := dataToPool(d)
	record.Id = currentRecord.Id

	if err != nil {
		return diag.FromErr(err)
	}

	updatedRecord, err := c.UpdatePool(record)
	if err != nil {
		return diag.FromErr(err)
	}

	return poolToData(updatedRecord, d)
}

func resourcePoolDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*client.Mikrotik)
	id := d.Id()

	err := c.DeletePool(id)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

func dataToPool(d *schema.ResourceData) *client.Pool {
	record := new(client.Pool)

	record.Name = d.Get("name").(string)
	record.Ranges = d.Get("ranges").(string)
	record.Comment = d.Get("comment").(string)

	return record
}

func poolToData(record *client.Pool, d *schema.ResourceData) diag.Diagnostics {
	values := map[string]interface{}{
		"name":    record.Name,
		"ranges":  record.Ranges,
		"comment": record.Comment,
	}

	d.SetId(record.Id)

	var diags diag.Diagnostics

	for key, value := range values {
		if err := d.Set(key, value); err != nil {
			diags = append(diags, diag.Errorf("failed to set %s: %v", key, err)...)
		}
	}

	return diags
}
